### ISSUE TITLE
issue with last 2.3-stable release

### ISSUE THREAD

**Issue by stefanpenner** [ember-cli/broccoli-concat#79]
forgot an import, fixing..

**Comment by stefanpenner** [comment]
should be fixed, may require:

```
npm cache clear
rm -rf node_modules
npm install
```

**Comment by stefanpenner** [comment]
stack trace in question was:

```js
ReferenceError: mkdirp is not defined
    at /Users/spenner/src/ef4/fast-sourcemap-concat/lib/source-map.js:414:9
    at initializePromise (/Users/spenner/src/ef4/fast-sourcemap-concat/node_modules/rsvp/dist/rsvp.js:588:5)
    at new Promise (/Users/spenner/src/ef4/fast-sourcemap-concat/node_modules/rsvp/dist/rsvp.js:1076:31)
    at SourceMap.end (/Users/spenner/src/ef4/fast-sourcemap-concat/lib/source-map.js:379:10)
    at ConcatWithMaps.build (/Users/spenner/tmp/my-cool-app-2/node_modules/broccoli-concat/concat.js:89:22)
    at /Users/spenner/tmp/my-cool-app-2/node_modules/broccoli-caching-writer/index.js:149:21
    at tryCatch (/Users/spenner/tmp/my-cool-app-2/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/Users/spenner/tmp/my-cool-app-2/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/Users/spenner/tmp/my-cool-app-2/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/Users/spenner/tmp/my-cool-app-2/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

----

hopefully this helps people searching/googling find this
